version: "3.3"
services:
  backend:
    container_name: backend
    image: backend
    networks:
      - network
    volumes:
    - /var/lib/jenkins/workspace/docker-pipeline/backend:/app
  frontend:
    container_name: frontend
    image: frontend
    ports:
      - "80:80"
    networks:
      - network
    volumes:
    - /var/lib/jenkins/workspace/docker-pipeline/frontend:/usr/share/nginx/html
    depends_on:
      - backend
networks:
  network:
    driver: bridge
