version: "3.8"
services:
  backend:
    container_name: backend-2
    image: app-backend
    networks:
      - app-network
    volumes:
    - /var/lib/jenkins/workspace/docker-pipeline/backend:/app
  frontend:
    container_name: frontend
    image: app-frontend
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:
    - /var/lib/jenkins/workspace/docker-pipeline/frontend:/usr/share/nginx/html
    depends_on:
      - backend
networks:
  app-network:
    driver: bridge
